/**
 * PEGAR A IDADE DA PESSOA
 * SE IDADE MAIOR IGUAL A 0(ZERO) E MENOR QUE 15
 *  | -> NÃO PODE VOTAR
 * SENÃO, SE IDADE MAIOR IGUAL A 16 E MENOR QUE 50
 *  | -> PODE VOTAR FILA NORMAL
 * SENÃO SE IDADE MAIOR IGUAL A 50 E MENOR QUE 70
 *  | -> PODE VOTAR FILA PRESENCIAL
 * SENÃO SE IDADE MAIOR IGUAL A 70
 *  | -> NÃO PRECISA  
 */

